// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05d1cxzcDD_b376fKQ1nW1zXChzpDh6M',
    appId: '1:1085793170043:android:859cd72d419aea7e8f28de',
    messagingSenderId: '1085793170043',
    projectId: 'foodninja-6b791',
    databaseURL: 'https://foodninja-6b791-default-rtdb.firebaseio.com',
    storageBucket: 'foodninja-6b791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_q_vbTy1Vie61OywJjFr_Rx_5qTfxdYg',
    appId: '1:1085793170043:ios:0e6e0dbce88d41978f28de',
    messagingSenderId: '1085793170043',
    projectId: 'foodninja-6b791',
    databaseURL: 'https://foodninja-6b791-default-rtdb.firebaseio.com',
    storageBucket: 'foodninja-6b791.firebasestorage.app',
    iosBundleId: 'com.example.foodNinja',
  );

}